//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSC.Web.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryProfile
    {
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> IsoNumeric { get; set; }
        public string IsoAlpha3 { get; set; }
        public string FipsCode { get; set; }
        public string Continent { get; set; }
        public string ContinentName { get; set; }
        public string Capital { get; set; }
        public Nullable<int> AreaInSqKm { get; set; }
        public Nullable<int> Population { get; set; }
        public string CurrencyCode { get; set; }
        public string Languages { get; set; }
        public int GeoNameId { get; set; }
        public Nullable<double> West { get; set; }
        public Nullable<double> North { get; set; }
        public Nullable<double> East { get; set; }
        public Nullable<double> South { get; set; }
        public string MapServiceURL { get; set; }
        public System.Data.Spatial.DbGeometry Geom { get; set; }
    
        public virtual GeoName GeoName { get; set; }
    }
}
