//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSC.Web.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandForcast
    {
        public int DemandForcastAnalysisId { get; set; }
        public Nullable<int> GeoNameId { get; set; }
        public Nullable<int> Radius { get; set; }
        public Nullable<int> TotalPopulation { get; set; }
        public Nullable<int> PopulationCoveredInCatachment { get; set; }
        public Nullable<int> PopulationOutsideOfCatachment { get; set; }
    
        public virtual GeoName GeoName { get; set; }
    }
}
