//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSC.Web.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demograhic
    {
        public int DemographicId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TotalPopulation { get; set; }
        public Nullable<int> Births { get; set; }
        public Nullable<int> Infant { get; set; }
        public Nullable<int> Under5 { get; set; }
        public Nullable<int> SchoolAge { get; set; }
        public Nullable<int> Female { get; set; }
        public Nullable<int> Birthing { get; set; }
        public Nullable<int> Pregnant { get; set; }
        public Nullable<int> GeoNamesId { get; set; }
    
        public virtual GeoName GeoName { get; set; }
    }
}
