//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSC.Web.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoName
    {
        public GeoName()
        {
            this.Demograhics = new HashSet<Demograhic>();
            this.ImunizationLocations = new HashSet<ImunizationLocation>();
            this.Schedules = new HashSet<Schedule>();
            this.DemandForcasts = new HashSet<DemandForcast>();
        }
    
        public int GeoNameId { get; set; }
        public string Name { get; set; }
        public string AsciiName { get; set; }
        public string AlternateNames { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string FeatureClass { get; set; }
        public string FeatureCode { get; set; }
        public string CountryCode { get; set; }
        public string CC2 { get; set; }
        public string Admin1Code { get; set; }
        public string Admin2Code { get; set; }
        public string Admin3Code { get; set; }
        public string Admin4Code { get; set; }
        public Nullable<int> Popuation { get; set; }
        public Nullable<int> Elevation { get; set; }
        public Nullable<int> Gtopo30 { get; set; }
        public string Timezone { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public System.Data.Spatial.DbGeometry Geom { get; set; }
    
        public virtual CountryProfile CountryProfile { get; set; }
        public virtual ICollection<Demograhic> Demograhics { get; set; }
        public virtual ICollection<ImunizationLocation> ImunizationLocations { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<DemandForcast> DemandForcasts { get; set; }
    }
}
