//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSC.Web.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImunizationLocation
    {
        public int ImunizationLocationId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string RefrigSpace { get; set; }
        public string FreezerSpace { get; set; }
        public string ColdStoragSpec { get; set; }
        public int CatchmentId { get; set; }
        public Nullable<int> GeoNameId { get; set; }
    
        public virtual GeoName GeoName { get; set; }
    }
}
