//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSC.Web.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public string VaccineName { get; set; }
        public string Abbreviation { get; set; }
        public string VaccinePresentation { get; set; }
        public string AdministrationMethod { get; set; }
        public string Presentation { get; set; }
        public Nullable<int> GeoNamesId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DosagePerVial { get; set; }
        public Nullable<int> DosageTotal { get; set; }
        public string Dosage1Age { get; set; }
        public string Dosage2Age { get; set; }
        public string Dosage3Age { get; set; }
        public string Dosage4Age { get; set; }
        public string Dosage5Age { get; set; }
    
        public virtual GeoName GeoName { get; set; }
    }
}
