//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSC.Web.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SigmaContext : DbContext
    {
        public SigmaContext()
            : base("name=SigmaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CountryProfile> CountryProfiles { get; set; }
        public DbSet<Demograhic> Demograhics { get; set; }
        public DbSet<GeoName> GeoNames { get; set; }
        public DbSet<ImunizationLocation> ImunizationLocations { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<DemandForcast> DemandForcasts { get; set; }
        public DbSet<CountryBoundary> CountryBoundaries { get; set; }
    }
}
